apiVersion: v1
kind: Pod # the object type
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client # temporary change to make work, should be able to use the shaya one
      ports:
        - containerPort: 3000