apiVersion: v1
kind: Pod # the object type
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: shayaajz/multi-client
      ports:
        - containerPort: 3000