apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:  #to know what set of pods it is supposed to be providing a service to
    component: web
  ports:
    - port: 3000 # how the different pods connect to the pod
      targetPort: 3000 # port on the target pod that we are providing access to.(could have been not 3000)



